// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOF7HNVtCJw3u4f33SYHoVd_-1Xi0l9Oo',
    appId: '1:285147283835:web:56a1fc74bd13b1a0537dde',
    messagingSenderId: '285147283835',
    projectId: 'chat-app-86710',
    authDomain: 'chat-app-86710.firebaseapp.com',
    storageBucket: 'chat-app-86710.firebasestorage.app',
    measurementId: 'G-7RW6J1HGG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLhgkmncwejO7xWUcOIrjHnh47M9-EG4A',
    appId: '1:285147283835:android:76a29999621d1b26537dde',
    messagingSenderId: '285147283835',
    projectId: 'chat-app-86710',
    storageBucket: 'chat-app-86710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPS8QjaMtEHHqCfo8MCtejMNY31ZytiJg',
    appId: '1:285147283835:ios:6e569d6ac9e1a1f4537dde',
    messagingSenderId: '285147283835',
    projectId: 'chat-app-86710',
    storageBucket: 'chat-app-86710.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPS8QjaMtEHHqCfo8MCtejMNY31ZytiJg',
    appId: '1:285147283835:ios:6e569d6ac9e1a1f4537dde',
    messagingSenderId: '285147283835',
    projectId: 'chat-app-86710',
    storageBucket: 'chat-app-86710.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOF7HNVtCJw3u4f33SYHoVd_-1Xi0l9Oo',
    appId: '1:285147283835:web:f6f0cbad0c8c9dab537dde',
    messagingSenderId: '285147283835',
    projectId: 'chat-app-86710',
    authDomain: 'chat-app-86710.firebaseapp.com',
    storageBucket: 'chat-app-86710.firebasestorage.app',
    measurementId: 'G-E37S01NFZL',
  );

}